// As páginas SEO: uma rota por intenção de busca, cada uma com texto,
// exemplos, funcionalidades e perguntas da rotina daquela busca. A
// estrutura vive aqui; o title, a description e o Open Graph podem ser
// sobrescritos pela plataforma (tabela seo_pages, 116).
//
// Campos: rota, tipo ('principal' | 'profissao'), kicker, h1 (linhas),
// sub, provas (3 chips), foto + alt + bilhete, mock ('desktop' |
// 'celular' | null), blocos [{titulo, texto, itens[]}], funcoes
// [{icone, titulo, texto}] (ícone por nome, resolvido na tela), faixa
// {titulo, texto, foto}, faq [[p, r]], artigos (slugs), cta {rotulo,
// tipo}, seo_title, meta_description.

export const PAGINAS_SEO = [
  {
    rota: '/sistema-para-salao-de-beleza', tipo: 'principal', kicker: 'Sistema para salão de beleza',
    h1: ['Toda a operação', 'do seu salão', 'em um só lugar.'],
    sub: 'Agenda, equipe, clientes, WhatsApp, retorno e pagamentos organizados em uma experiência feita para a rotina de quem vive da beleza.',
    provas: ['Múltiplas profissionais', 'Funciona no celular', 'Comece hoje mesmo'],
    foto: 'profissional', alt: 'profissional de beleza sorrindo no salão, com o app MIMO aberto no celular', bilhete: 'mais organização pro seu dia a dia',
    mock: 'desktop', mockTitulo: 'Uma visão completa do seu salão.', mockTexto: 'Veja a agenda de todas as profissionais, gerencie serviços, bloqueios, encaixes e acompanhe a operação em tempo real.',
    seo_title: 'Sistema para Salão de Beleza | MIMO',
    meta_description: 'Sistema para salão de beleza com agenda multi-profissional, equipe, clientes, WhatsApp, lista de espera, sinal e comanda. Organize a operação inteira com a MIMO.',
    blocos: [
      { titulo: 'Agenda multi-profissional', texto: 'Cada profissional numa coluna, cada horário num cartão. A disponibilidade considera serviço, duração, bloqueios e pausas, então o salão nunca oferece um horário que não existe.', itens: ['Agenda geral e por profissional', 'Bloqueios, folgas e pausas', 'Encaixes sem bagunçar o dia', 'Vários serviços num horário só'] },
      { titulo: 'Serviços e equipe', texto: 'Serviços com preço, duração e quem executa. A profissional entra pelo link da equipe e encontra a própria agenda pronta, com o vínculo e as permissões que o salão definiu.', itens: ['Duração real por serviço', 'Vínculo como configuração inicial', 'Permissões por profissional', 'App próprio para cada uma'] },
      { titulo: 'Clientes e retorno', texto: 'Histórico por serviço e por profissional. Quem deveria voltar, quem sumiu e quem tem manutenção vencendo aparecem como ação, não como relatório.', itens: ['Histórico e preferências', 'Retorno no prazo certo', 'Origem da cliente preservada', 'Avaliação depois do atendimento'] },
      { titulo: 'WhatsApp, lista de espera e pagamentos', texto: 'Confirmação, lembrete e remarcação ligados ao horário. Cancelou, a vaga vai para quem estava esperando. Sinal por Pix e comanda que fecha com o repasse separado.', itens: ['Confirmação e lembrete pelo WhatsApp', 'Lista de espera por serviço e período', 'Sinal fixo ou porcentagem', 'Comanda com repasse por profissional'] },
    ],
    funcoes: [['CalendarDays', 'Agenda', 'Múltiplas profissionais, bloqueios, encaixes e vários serviços.'], ['Users', 'Equipe', 'Vínculos, horários, serviços e permissões por profissional.'], ['Heart', 'Clientes', 'Histórico, preferências e retornos.'], ['MessageCircle', 'WhatsApp', 'Confirmações, lembretes e comunicação no contexto da agenda.'], ['Clock', 'Lista de espera', 'A vaga que abriu vai para quem combina com ela.'], ['Wallet', 'Pagamentos', 'Sinal, comanda e repasse ligados ao atendimento.']],
    faixa: { titulo: 'Feito para salões reais. Como o seu.', texto: 'A MIMO foi criada com base na rotina de salões de beleza, com linguagem simples e funcionalidades que realmente fazem diferença no dia a dia.', foto: 'equipe', bilhete: 'menos bagunça, mais tempo pro que importa' },
    faq: [
      ['Serve para salão com várias profissionais?', 'Sim. Cada profissional tem a própria agenda dentro da estrutura do salão, e o salão enxerga todas juntas na agenda geral.'],
      ['Quem configura a agenda da profissional?', 'O salão: vínculo, serviços, horários e permissões. A profissional entra pelo link da equipe e já encontra tudo pronto.'],
      ['A cliente precisa de aplicativo na loja?', 'Não. Ela entra pelo seu QR, código ou link, no navegador, e pode adicionar à tela inicial como um app.'],
      ['Quanto custa?', 'R$ 49,90 por mês, mais R$ 9,90 por profissional ativa na agenda. Autônoma é grátis.'],
    ],
    artigos: ['como-organizar-agenda-salao-de-beleza', 'agenda-multi-profissional-salao', 'como-escolher-sistema-para-salao-de-beleza'],
    cta: { rotulo: 'Criar meu salão', tipo: 'salao' },
  },
  {
    rota: '/agenda-online-para-salao-de-beleza', tipo: 'principal', kicker: 'Agenda online para salão',
    h1: ['Uma agenda que entende', 'como o salão', 'realmente funciona.'],
    sub: 'Horários por profissional, duração de serviço, bloqueios, encaixes, remarcação, lista de espera e confirmação. Tudo o que a agenda de papel não consegue segurar.',
    provas: ['Cliente marca sozinha', 'Confirmação pelo WhatsApp', 'Vaga cancelada não morre'],
    foto: 'agenda-celular', alt: 'dois celulares com a agenda do dia e a lista de serviços da MIMO', bilhete: 'sua cliente marca sozinha',
    mock: 'desktop', mockTitulo: 'O dia inteiro numa tela.', mockTexto: 'Colunas por profissional, cartões por horário, pedidos para confirmar e vagas abertas. Arraste para remarcar.',
    seo_title: 'Agenda Online para Salão de Beleza | MIMO',
    meta_description: 'Agenda online para salão de beleza: a cliente marca pelo seu QR ou link, o salão vê todas as profissionais, confirma pelo WhatsApp e preenche vagas com a lista de espera.',
    blocos: [
      { titulo: 'Horários que respeitam a duração', texto: 'Escova de 45 minutos ocupa 45 minutos. Progressiva de três horas ocupa três horas. A agenda só oferece um horário que cabe no serviço escolhido, com a profissional escolhida.', itens: ['Duração por serviço e por profissional', 'Intervalo mínimo entre atendimentos', 'Antecedência mínima para marcar', 'Horário de cada profissional, não só do salão'] },
      { titulo: 'Bloqueios, pausas e encaixes', texto: 'Almoço, folga, curso e compromisso ficam bloqueados na agenda certa. Encaixe entra onde sobra espaço real, sem empurrar atraso para a próxima cliente.', itens: ['Bloqueio individual por profissional', 'Pausas recorrentes', 'Encaixe pelo balcão ou pelo app da profissional', 'Remarcar arrastando o cartão'] },
      { titulo: 'Confirmação e lista de espera', texto: 'O pedido de horário pode ser aceito na hora, pela casa ou pela profissional, com prazo. Na véspera sai a confirmação pelo WhatsApp. Cancelou, a vaga aparece para quem estava esperando aquele serviço.', itens: ['Aceite automático, pela casa ou pela profissional', 'Confirmação e lembrete no WhatsApp', 'Lista de espera por serviço, profissional e período', 'Remarcação sem conversa perdida'] },
    ],
    funcoes: [['CalendarDays', 'Agenda geral', 'Todas as profissionais numa tela só.'], ['UserRound', 'Agenda por profissional', 'Cada uma com os próprios horários no app.'], ['PauseCircle', 'Bloqueios e pausas', 'Almoço, folga, férias, indisponível.'], ['CalendarPlus', 'Encaixes', 'Aproveite o espaço que sobrou.'], ['Clock', 'Lista de espera', 'Vaga cancelada vai para quem combina.'], ['MessageCircle', 'Confirmação', 'Pelo WhatsApp, ligada ao horário.']],
    faixa: { titulo: 'Da agenda ao relacionamento.', texto: 'A agenda é onde tudo começa. A MIMO liga o horário ao histórico da cliente, à profissional que atendeu e ao pagamento.', foto: 'cliente', bilhete: 'rotina no lugar' },
    faq: [
      ['A cliente marca sozinha?', 'Sim. Ela entra pelo seu QR ou link, escolhe serviço, profissional, dia e horário entre os que estão livres de verdade.'],
      ['Posso aprovar antes de confirmar?', 'Pode. O salão escolhe: confirmação automática, aprovação pela casa com prazo, ou cada profissional decide os próprios pedidos.'],
      ['E quando a cliente cancela?', 'A vaga aparece no quadro do salão junto com as clientes da lista de espera que combinam com aquele serviço e horário.'],
      ['Funciona com agenda de papel junto?', 'Funciona, mas o ganho vem de tirar a informação da cabeça e do papel. Encaixes feitos pelo balcão entram na mesma agenda que a cliente vê.'],
    ],
    artigos: ['como-organizar-agenda-salao-de-beleza', 'como-reduzir-horarios-vagos-salao', 'agenda-multi-profissional-salao'],
    cta: { rotulo: 'Começar agora', tipo: 'salao' },
  },
  {
    rota: '/app-para-profissional-de-beleza', tipo: 'principal', kicker: 'App para profissional de beleza',
    h1: ['Sua agenda,', 'seus clientes,', 'no seu celular.'],
    sub: 'A conta de autônoma da MIMO é grátis: agenda, serviços, horários, clientes, QR e link próprios. Sem menu de equipe, sem estrutura que você não usa.',
    provas: ['100% grátis para autônomas', 'Funciona no celular', 'Comece em minutos'],
    foto: 'profissional', alt: 'profissional autônoma mostrando a agenda no celular', bilhete: 'mais tempo para o que você ama',
    mock: 'celular', mockTitulo: 'Tudo o que uma autônoma precisa.', mockTexto: 'Agenda, serviços, clientes e retorno num app que cabe na rotina.',
    seo_title: 'App para Profissional de Beleza Autônoma (Grátis) | MIMO',
    meta_description: 'App grátis para profissional de beleza autônoma: agenda online, serviços e preços, clientes com histórico, QR e link próprios e retorno de clientes. Sem mensalidade.',
    blocos: [
      { titulo: 'Sua agenda, do seu jeito', texto: 'Defina os dias e horários em que atende, a duração de cada serviço e a antecedência mínima. A cliente vê só o que está livre e marca sozinha.', itens: ['Horários por dia da semana', 'Bloqueios para o que não é atendimento', 'Pedido de horário para você aceitar, se quiser', 'Aviso no celular a cada novo horário'] },
      { titulo: 'Serviços, preços e clientes', texto: 'Cadastre o que faz, com preço e tempo. Cada cliente fica com o histórico do que fez com você, e a MIMO lembra quem está na hora de voltar.', itens: ['Serviços com preço e duração', 'Histórico por cliente', 'Retorno por tipo de serviço', 'Avaliação depois de cada atendimento'] },
      { titulo: 'Seu QR e seu link', texto: 'A cliente entra pelo seu código, no balcão, no cartão ou no Instagram. Ela fica vinculada a você, não a uma vitrine genérica.', itens: ['QR para imprimir', 'Link para a bio do Instagram', 'Página própria com serviços', 'Sem marketplace, sem concorrente ao lado'] },
    ],
    funcoes: [['CalendarDays', 'Agenda', 'Seus horários organizados.'], ['Scissors', 'Serviços', 'Cadastre seus serviços e valores.'], ['Heart', 'Clientes', 'Histórico e preferências.'], ['QrCode', 'QR e link próprio', 'Divulgue sua agenda onde quiser.'], ['RotateCcw', 'Retorno', 'Veja quem já deveria voltar.'], ['Bell', 'Avisos', 'Novo horário, cancelamento, avaliação.']],
    faixa: { titulo: 'Feita para a sua realidade.', texto: 'A MIMO entende a rotina de quem trabalha com beleza de forma independente e oferece o que você realmente precisa, sem menus que não fazem sentido para o seu dia a dia.', foto: 'lifestyle', bilhete: 'mais clientes, mais organização, mais você' },
    faq: [
      ['É grátis mesmo?', 'É. A conta de autônoma não tem mensalidade nem cartão: uma agenda, serviços, clientes, QR e link próprios.'],
      ['E se um dia eu abrir um salão?', 'A mesma conta vira salão: você adiciona a equipe e passa para o plano MIMO Pro, sem perder clientes nem histórico.'],
      ['Preciso baixar aplicativo?', 'Não. Abre no navegador e pode ser adicionado à tela inicial do celular, com aviso e tudo, como um app instalado.'],
      ['Minha cliente precisa de conta?', 'Ela cria uma conta simples ao entrar pelo seu QR ou link, e a partir daí marca, remarca e avalia sozinha.'],
    ],
    artigos: ['como-fazer-clientes-voltarem-salao', 'como-reduzir-horarios-vagos-salao', 'como-organizar-agenda-salao-de-beleza'],
    cta: { rotulo: 'Criar agenda grátis', tipo: 'autonoma' },
  },
  {
    rota: '/agenda-para-manicure', tipo: 'profissao', kicker: 'Agenda para manicure',
    h1: ['Sua agenda', 'de manicure mais', 'simples e completa.'],
    sub: 'Organize seus horários, clientes e serviços com a MIMO. Manutenção no prazo, cliente que volta e horário que não fica vazio. Sem complicação e sem custo.',
    provas: ['100% grátis para autônomas', 'Funciona no celular', 'Comece em minutos'],
    foto: 'lifestyle', alt: 'bancada de manicure com esmaltes, pincéis e o app MIMO no celular', bilhete: 'mais tempo pra você',
    mock: 'celular', mockTitulo: 'Tudo o que uma manicure precisa.', mockTexto: 'A MIMO traz o essencial para você organizar sua rotina, atender melhor suas clientes e fazer elas voltarem.',
    seo_title: 'Agenda para Manicure: online e grátis | MIMO',
    meta_description: 'Agenda online para manicure: manutenção em dia, clientes recorrentes com histórico, serviços e preços, horários e link próprio para a cliente marcar sozinha. Grátis.',
    blocos: [
      { titulo: 'Manutenção no prazo certo', texto: 'Gel, fibra, alongamento e esmaltação têm ciclos diferentes. A MIMO guarda o último atendimento de cada cliente e avisa quando a manutenção está chegando, antes de ela sumir.', itens: ['Retorno por tipo de serviço', 'Último atendimento de cada cliente', 'Mensagem com contexto, não disparo', 'Cliente marca o próximo pelo seu link'] },
      { titulo: 'Duração que não atrasa o dia', texto: 'Manicure simples, pé e mão, alongamento e blindagem ocupam tempos diferentes. Cadastre a duração real e a agenda só oferece o que cabe.', itens: ['Serviços com preço e tempo', 'Combinação de mão e pé num horário só', 'Intervalo entre clientes, se você quiser', 'Bloqueio para almoço e folga'] },
      { titulo: 'Clientes recorrentes, sem caderno', texto: 'Cada cliente com o histórico do que fez, a cor que gostou e a observação que você anotou. Quando ela volta, você lembra.', itens: ['Histórico por cliente', 'Observações do atendimento', 'Avaliação depois de cada serviço', 'QR no espelho, link no Instagram'] },
    ],
    funcoes: [['CalendarDays', 'Agenda', 'Seus horários organizados.'], ['Hand', 'Serviços', 'Mão, pé, alongamento, manutenção, com preço e tempo.'], ['Heart', 'Clientes', 'Histórico e preferências.'], ['QrCode', 'QR e link próprio', 'Divulgue sua agenda onde quiser.'], ['RotateCcw', 'Retorno', 'Veja quem já deveria voltar.']],
    faixa: { titulo: 'Feita para a sua realidade.', texto: 'A MIMO entende a rotina de quem trabalha com beleza de forma independente e oferece o que você realmente precisa, sem menus que não fazem sentido para o seu dia a dia.', foto: 'cliente', bilhete: 'mais clientes, mais organização, mais você' },
    faq: [
      ['Serve para quem atende em casa?', 'Serve. A agenda é sua, o endereço é o que você definir, e a cliente marca pelo seu link.'],
      ['Consigo marcar mão e pé no mesmo horário?', 'Consegue. A cliente escolhe os dois serviços e a agenda soma o tempo.'],
      ['E se eu trabalhar num salão também?', 'Você pode ter a sua agenda de autônoma e entrar na equipe de um salão pelo link dele. Cada relação fica separada.'],
      ['Quanto custa?', 'Nada. A conta de autônoma é gratuita.'],
    ],
    artigos: ['como-fazer-clientes-voltarem-salao', 'como-reduzir-horarios-vagos-salao', 'sinal-no-agendamento-salao'],
    cta: { rotulo: 'Criar agenda grátis', tipo: 'autonoma' },
  },
  {
    rota: '/agenda-para-cabeleireira', tipo: 'profissao', kicker: 'Agenda para cabeleireira',
    h1: ['Corte, escova,', 'química: uma agenda', 'que cabe tudo.'],
    sub: 'Serviços longos, combinações de serviços, química com tempo de pausa e retorno de cliente. A MIMO organiza a agenda de cabeleireira do jeito que ela é.',
    provas: ['Serviços longos sem conflito', 'Combinações num horário só', 'Grátis para autônomas'],
    foto: 'salao', alt: 'salão de beleza com cadeiras e espelhos iluminados', bilhete: 'agenda cheia, dia tranquilo',
    mock: 'desktop', mockTitulo: 'Cada química no tempo certo.', mockTexto: 'Coloração, progressiva e mechas ocupam o tempo que precisam. A agenda mostra o que ainda cabe no dia.',
    seo_title: 'Agenda para Cabeleireira: serviços longos e retorno | MIMO',
    meta_description: 'Agenda online para cabeleireira: corte, escova, coloração e progressiva com duração real, combinações de serviços, retorno de clientes e agenda por profissional. Grátis para autônoma.',
    blocos: [
      { titulo: 'Serviços longos, sem empurrar o dia', texto: 'Uma progressiva de três horas não pode virar duas na agenda. Cadastre a duração real de cada serviço, e a MIMO só oferece horários em que ele cabe inteiro.', itens: ['Duração por serviço, ajustável por profissional', 'Coloração, mechas, progressiva, tratamento', 'Antecedência mínima para química', 'Bloqueio para o tempo de pausa'] },
      { titulo: 'Combinações de serviços', texto: 'Corte + escova, coloração + hidratação, mechas + corte. A cliente escolhe os serviços e a agenda soma o tempo e o valor. No fechamento, uma comanda só.', itens: ['Vários serviços num agendamento', 'Preço e tempo somados', 'Serviço adicionado no salão entra na mesma comanda', 'Avaliação por serviço'] },
      { titulo: 'Retorno de retoque e manutenção', texto: 'Raiz, retoque de cor, manutenção de progressiva. Cada serviço tem um ritmo de retorno. A MIMO avisa quem está na época de voltar, com contexto.', itens: ['Retorno por tipo de serviço', 'Histórico de cores e observações', 'Mensagem pelo WhatsApp com o serviço certo', 'Cliente marca o próximo pelo seu link'] },
    ],
    funcoes: [['Scissors', 'Serviços', 'Corte, escova, química, tratamento, com tempo real.'], ['CalendarDays', 'Agenda', 'Por profissional e do salão inteiro.'], ['Heart', 'Clientes', 'Histórico, cores e observações.'], ['RotateCcw', 'Retorno', 'Raiz e manutenção no prazo.'], ['Receipt', 'Comanda', 'Vários serviços, uma conta.'], ['MessageCircle', 'WhatsApp', 'Confirmação e lembrete no horário.']],
    faixa: { titulo: 'Sozinha ou com equipe.', texto: 'Cabeleireira autônoma usa a MIMO de graça. Salão com várias cabeleireiras vê todas na agenda geral, cada uma com a própria agenda no app.', foto: 'equipe', bilhete: 'cada uma com a sua agenda' },
    faq: [
      ['Dá para cadastrar tempo diferente para cada profissional?', 'Dá. O serviço tem um tempo padrão e cada profissional pode ter o seu.'],
      ['A cliente pode marcar dois serviços de uma vez?', 'Pode. Ela escolhe corte e escova, por exemplo, e a agenda reserva o tempo somado.'],
      ['Como fica o retorno de raiz?', 'Cada serviço tem um intervalo de retorno. Quando chega a época, a cliente aparece na lista de quem deveria voltar.'],
      ['Quanto custa?', 'Autônoma é grátis. Salão paga R$ 49,90 por mês mais R$ 9,90 por profissional ativa.'],
    ],
    artigos: ['como-organizar-agenda-salao-de-beleza', 'como-fazer-clientes-voltarem-salao', 'agenda-multi-profissional-salao'],
    cta: { rotulo: 'Começar agora', tipo: null },
  },
  {
    rota: '/agenda-para-lash-designer', tipo: 'profissao', kicker: 'Agenda para lash designer',
    h1: ['Aplicação e', 'manutenção de cílios', 'no prazo certo.'],
    sub: 'Cílios têm ciclo: aplicação, manutenção em duas ou três semanas, remoção. A MIMO organiza a agenda de lash designer em torno desse ritmo, com cliente que volta e horário que não fica vazio.',
    provas: ['Manutenção no ciclo certo', 'Sinal para segurar o horário', 'Grátis para autônomas'],
    foto: 'cliente', alt: 'cliente marcando o próximo horário no celular com a profissional', bilhete: 'manutenção em dia',
    mock: 'celular', mockTitulo: 'O ciclo dos cílios na agenda.', mockTexto: 'Aplicação hoje, manutenção em vinte dias. A MIMO lembra a cliente antes de os fios caírem.',
    seo_title: 'Agenda para Lash Designer: manutenção e recorrência | MIMO',
    meta_description: 'Agenda online para lash designer: aplicação e manutenção de cílios com tempo real, retorno automático no ciclo certo, sinal por Pix para segurar o horário e link próprio. Grátis.',
    blocos: [
      { titulo: 'Tempo de serviço de verdade', texto: 'Aplicação fio a fio leva mais de duas horas. Manutenção, pouco mais de uma. Remoção, meia. A agenda respeita cada tempo e só oferece horários em que o serviço cabe.', itens: ['Aplicação, manutenção, remoção com tempos próprios', 'Volume brasileiro, híbrido, egípcio como serviços separados', 'Intervalo entre clientes para preparar a maca', 'Bloqueio para cursos e folgas'] },
      { titulo: 'Recorrência com contexto', texto: 'A MIMO guarda a data da aplicação e sugere a manutenção no intervalo que você definir. A cliente recebe o aviso na hora certa e marca pelo seu link.', itens: ['Retorno por serviço, em dias', 'Histórico de técnica e curvatura', 'Aviso pelo WhatsApp com o serviço', 'Avaliação depois de cada atendimento'] },
      { titulo: 'Sinal para horário longo', texto: 'Uma aplicação de duas horas que não aparece custa a tarde. Com sinal por Pix, o horário só fica reservado quando o pagamento entra, e o restante fecha no atendimento.', itens: ['Sinal fixo ou porcentagem', 'Regra de remarcação clara antes de pagar', 'Restante no atendimento', 'Cancelou, a vaga vai para a lista de espera'] },
    ],
    funcoes: [['Eye', 'Serviços', 'Aplicação, manutenção, remoção, com tempo real.'], ['CalendarDays', 'Agenda', 'Só horários em que o serviço cabe.'], ['RotateCcw', 'Retorno', 'Manutenção no ciclo certo.'], ['Wallet', 'Sinal', 'Pix para segurar o horário longo.'], ['Heart', 'Clientes', 'Histórico de técnica e preferências.'], ['QrCode', 'QR e link', 'Na bio, no cartão, no espelho.']],
    faixa: { titulo: 'Feita para a sua realidade.', texto: 'A MIMO entende a rotina de quem trabalha com cílios e sobrancelhas de forma independente e oferece o que você precisa, sem menus que não fazem sentido para o seu dia a dia.', foto: 'lifestyle', bilhete: 'mais clientes, mais organização, mais você' },
    faq: [
      ['Consigo configurar o intervalo de manutenção?', 'Consegue, por serviço e em dias. Aplicação com retorno em 21 dias, por exemplo.'],
      ['Posso cobrar sinal só na aplicação?', 'Pode. O sinal é configurado pelo negócio e vale para os serviços em que fizer sentido.'],
      ['Atendo cílios e sobrancelhas: dá para separar?', 'Dá. Cada serviço tem categoria, tempo e retorno próprios, na mesma agenda.'],
      ['Quanto custa?', 'Autônoma é grátis. Não tem cartão nem mensalidade.'],
    ],
    artigos: ['como-fazer-clientes-voltarem-salao', 'sinal-no-agendamento-salao', 'como-reduzir-horarios-vagos-salao'],
    cta: { rotulo: 'Criar agenda grátis', tipo: 'autonoma' },
  },
  {
    rota: '/agenda-para-designer-de-sobrancelhas', tipo: 'profissao', kicker: 'Agenda para designer de sobrancelhas',
    h1: ['Design, henna e', 'brow lamination', 'na agenda certa.'],
    sub: 'Atendimentos curtos, muitos por dia, cliente que volta a cada três ou quatro semanas. A MIMO organiza a agenda de designer de sobrancelhas para encher o dia sem sobrepor horário.',
    provas: ['Muitos horários por dia', 'Retorno a cada 3 semanas', 'Grátis para autônomas'],
    foto: 'profissional', alt: 'profissional de beleza no salão com o celular na mão', bilhete: 'agenda cheia, sem aperto',
    mock: 'celular', mockTitulo: 'Um dia cheio, sem sobreposição.', mockTexto: 'Design de 30 minutos, henna de 45, lamination de uma hora. A agenda encaixa cada um no tempo certo.',
    seo_title: 'Agenda para Designer de Sobrancelhas | MIMO',
    meta_description: 'Agenda online para designer de sobrancelhas: design, henna e brow lamination com tempos próprios, retorno de clientes a cada ciclo, encaixes e link próprio para marcar. Grátis.',
    blocos: [
      { titulo: 'Atendimentos curtos, agenda cheia', texto: 'Quando cada atendimento leva meia hora, um horário perdido por dia vira muitos por mês. A MIMO mostra os espaços que sobraram e permite encaixe onde cabe.', itens: ['Serviços de 30, 45 e 60 minutos', 'Encaixe entre atendimentos', 'Antecedência mínima para marcar', 'Bloqueio para almoço e folga'] },
      { titulo: 'Retorno a cada ciclo', texto: 'Design e henna voltam em três ou quatro semanas. Lamination, em dois meses. A MIMO lembra a cliente no prazo de cada serviço, com o link para marcar.', itens: ['Retorno por serviço, em dias', 'Histórico de formato e cor de henna', 'Aviso pelo WhatsApp', 'Avaliação depois de cada atendimento'] },
      { titulo: 'Sua página, seu link', texto: 'Cliente nova chega pelo QR no espelho ou pelo link na bio. Ela fica vinculada a você e passa a marcar sozinha nos horários que você abriu.', itens: ['QR para imprimir', 'Link para o Instagram', 'Página com serviços e preços', 'Sem marketplace'] },
    ],
    funcoes: [['Eye', 'Serviços', 'Design, henna, lamination, com tempo próprio.'], ['CalendarDays', 'Agenda', 'Muitos horários, sem sobrepor.'], ['CalendarPlus', 'Encaixes', 'Aproveite o espaço que sobrou.'], ['RotateCcw', 'Retorno', 'A cada ciclo, com contexto.'], ['Heart', 'Clientes', 'Histórico e preferências.'], ['QrCode', 'QR e link', 'No espelho e na bio.']],
    faixa: { titulo: 'Feita para a sua realidade.', texto: 'A MIMO entende a rotina de quem atende muitas clientes por dia e oferece o que você precisa: agenda, retorno e link próprio, sem menus que não fazem sentido.', foto: 'cliente', bilhete: 'mais clientes, mais organização, mais você' },
    faq: [
      ['Dá para atender de 30 em 30 minutos?', 'Dá. A grade da agenda segue a duração dos seus serviços.'],
      ['Como funciona o retorno?', 'Cada serviço tem um intervalo em dias. Quando chega, a cliente aparece na lista de quem deveria voltar e pode receber um aviso pelo WhatsApp.'],
      ['Posso cobrar sinal?', 'Pode, se fizer sentido para você. Muitas designers só usam sinal em lamination e pacotes.'],
      ['Quanto custa?', 'Autônoma é grátis.'],
    ],
    artigos: ['como-fazer-clientes-voltarem-salao', 'como-reduzir-horarios-vagos-salao', 'como-organizar-agenda-salao-de-beleza'],
    cta: { rotulo: 'Criar agenda grátis', tipo: 'autonoma' },
  },
  {
    rota: '/agenda-para-esteticista', tipo: 'profissao', kicker: 'Agenda para esteticista',
    h1: ['Protocolos, sessões', 'e pacotes', 'numa agenda só.'],
    sub: 'Limpeza de pele, drenagem, massagem, pacotes de dez sessões. A MIMO organiza a agenda de esteticista com sessões longas, retorno por protocolo e sinal quando o horário merece.',
    provas: ['Sessões de 60 a 120 minutos', 'Retorno por protocolo', 'Grátis para autônomas'],
    foto: 'lifestyle', alt: 'bancada de estética com produtos, vela e o app MIMO no celular', bilhete: 'seu tempo também importa',
    mock: 'desktop', mockTitulo: 'Cada sessão no tempo certo.', mockTexto: 'Limpeza de pele de uma hora e meia, drenagem de uma hora. A agenda mostra o que ainda cabe no dia, por profissional.',
    seo_title: 'Agenda para Esteticista: sessões, pacotes e retorno | MIMO',
    meta_description: 'Agenda online para esteticista: sessões longas com duração real, retorno por protocolo, sinal por Pix para horários longos, histórico de cada cliente e link próprio para marcar. Grátis.',
    blocos: [
      { titulo: 'Sessões longas sem conflito', texto: 'Limpeza de pele, peeling, drenagem e massagem têm tempos diferentes e às vezes precisam de intervalo para preparar a sala. A MIMO só oferece horários em que a sessão cabe inteira.', itens: ['Duração real por procedimento', 'Intervalo entre sessões', 'Bloqueio para sala em uso', 'Antecedência mínima para marcar'] },
      { titulo: 'Retorno por protocolo', texto: 'Drenagem semanal, limpeza de pele mensal, manutenção de peeling a cada 15 dias. Cada serviço tem um ritmo, e a cliente é lembrada no prazo certo.', itens: ['Retorno por serviço, em dias', 'Histórico de sessões e observações', 'Aviso pelo WhatsApp', 'Avaliação depois de cada atendimento'] },
      { titulo: 'Sinal e pagamento ligados à sessão', texto: 'Sessão de duas horas que não aparece custa a tarde. Com sinal por Pix o horário só fica reservado quando o pagamento entra, e o restante fecha no atendimento, na mesma comanda.', itens: ['Sinal fixo ou porcentagem', 'Regra de remarcação clara', 'Restante no atendimento', 'Comanda com o histórico da sessão'] },
    ],
    funcoes: [['Flower2', 'Procedimentos', 'Facial, corporal, massagem, com tempo real.'], ['CalendarDays', 'Agenda', 'Só horários em que a sessão cabe.'], ['RotateCcw', 'Retorno', 'Por protocolo, no prazo.'], ['Wallet', 'Sinal', 'Pix para segurar o horário longo.'], ['Heart', 'Clientes', 'Histórico de sessões.'], ['QrCode', 'QR e link', 'Na recepção e na bio.']],
    faixa: { titulo: 'Sozinha ou na clínica.', texto: 'Esteticista autônoma usa a MIMO de graça. Clínica ou salão com várias profissionais vê todas na agenda geral, cada uma com a própria agenda no app.', foto: 'equipe', bilhete: 'cada uma com a sua agenda' },
    faq: [
      ['Consigo vender pacotes de sessões?', 'A MIMO organiza as sessões na agenda e o histórico de cada cliente. O controle de pacote pago em bloco é feito pela comanda e pelo histórico; um módulo próprio de pacotes está no caminho.'],
      ['Dá para bloquear a sala?', 'Dá. Bloqueio por profissional e por período cobre sala em uso, manutenção de equipamento e folga.'],
      ['Posso cobrar sinal em todos os procedimentos?', 'Pode, ou só nos longos. O sinal é configurado pelo negócio.'],
      ['Quanto custa?', 'Autônoma é grátis. Clínica ou salão paga R$ 49,90 por mês mais R$ 9,90 por profissional ativa.'],
    ],
    artigos: ['sinal-no-agendamento-salao', 'como-fazer-clientes-voltarem-salao', 'como-organizar-agenda-salao-de-beleza'],
    cta: { rotulo: 'Começar agora', tipo: null },
  },
]

// as páginas institucionais também têm SEO próprio e entram no sitemap
export const PAGINAS_INSTITUCIONAIS = [
  { rota: '/', tipo: 'home', titulo: 'Home', seo_title: 'MIMO | Sistema para Salão de Beleza e Agenda Online', meta_description: 'Organize agenda, clientes, equipe, WhatsApp, retorno e pagamentos com a MIMO. Sistema para salão de beleza e profissional autônoma. Plano grátis para autônomas.' },
  { rota: '/planos', tipo: 'institucional', titulo: 'Planos', seo_title: 'Planos e preços | MIMO', meta_description: 'Autônoma grátis. Salão por R$ 49,90/mês mais R$ 9,90 por profissional ativa na agenda. Sem orçamento, sem surpresa.' },
  { rota: '/sobre', tipo: 'institucional', titulo: 'Sobre a MIMO', seo_title: 'Sobre a MIMO | Beleza, organização e relacionamento', meta_description: 'A MIMO é um sistema de agenda e relacionamento para salões e profissionais de beleza, construído junto à rotina real de quem vive da beleza.' },
  { rota: '/contato', tipo: 'institucional', titulo: 'Contato', seo_title: 'Contato | MIMO', meta_description: 'Fale com a equipe da MIMO: dúvidas sobre o sistema para salão, a conta de autônoma ou parcerias.' },
  { rota: '/blog', tipo: 'blog', titulo: 'Blog', seo_title: 'Blog da MIMO | Agenda, clientes e gestão de salão', meta_description: 'Guias curtos e práticos para quem vive da beleza: agenda, clientes, equipe, WhatsApp e financeiro do salão.' },
  { rota: '/termos', tipo: 'institucional', titulo: 'Termos de uso', seo_title: 'Termos de uso | MIMO', meta_description: 'Termos de uso da MIMO.' },
  { rota: '/privacidade', tipo: 'institucional', titulo: 'Privacidade', seo_title: 'Política de privacidade | MIMO', meta_description: 'Política de privacidade da MIMO, pensada para a LGPD.' },
]

export function paginaSeoPorRota(rota) {
  return PAGINAS_SEO.find((p) => p.rota === rota) || null
}
